### PR TITLE
Added `group` method. Includes tests.

### PR DESCRIPTION
**Pull request by dolfelt**
This would make the Outbound integration much more useful to us. Let me know if there are any changes required. @gjohnson

### CODE REVIEW

**Comment by gjohnson** [comment]
Ping @ndhoule

**Comment by ndhoule** [comment]
Hey @dolfelt, can you point me to which part of the Outbound API this matches up with? I had a look at their API documentation and wasn't able to find any sort of grouping support.

If you could also send over some of your use cases and an example `#group` call, that'd be helpful in evaluating this, too.

Thanks!

**Comment by dolfelt** [comment]
@ndhoule The Outbound API doesn't support the `group` method. This is attaching all the traits from the group method to their user object. I'm doing something similar to what the Vero integration does.

https://github.com/segmentio/integration-vero/blob/master/lib/mapper.js#L61

The use case would be so that we don't have to fill our Segment user objects with Account/Group data but can still have it available to us in Outbound.

**Comment by chadworks** [comment]
In addition to attaching the group traits to the Outbound user object, it would be really helpful if the `track` call could also include a property `count` by default when it reports to Outbound since Outbound doesn't keep track of how many times an event has been tracked. If there was a `count` property sent to outbound, it would make setting up rules based on how many times an event has happened very easy, not to mention make Outbound much more powerful when used with Segment.

**Comment by stevenmiller888** [comment]
ping @ndhoule

**Comment by chadworks** [comment]
@ndhoule If you have questions about this, let @dolfelt or I know. We're trying to make Outbound work with all of the Segment trait data for group and identify calls. This shim does the trick for us and I'm sure others that are trying to feed Outbound with group and user data traits.

**Comment by amillet89** [comment]
hey @chadworks and @dolfelt- we'll merge this for now, although ideally we'd want Outbound to implement this functionality rather than rely on a workaround. let us know if you face any issues!

**Comment by dolfelt** [comment]
Thanks @amillet89! When do you think this will go live into the Segment event flow?

**Comment by chadworks** [comment]
@dolfelt Looks like its live. I see group.trait-name going into Outbound now.

**Comment by amillet89** [comment]
yep it went live earlier today!

**Pull request merged**
